; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{318DAB99-8627-4FE9-AE63-077F1E1848D3}
AppName=Sound Recorder
AppVersion=1.0
;AppVerName=Sound Recorder 1.0
AppPublisher=Alireza Hosseinzadeh
AppPublisherURL=https://github.com/alireza-turk-oglan/soundrecorder
AppSupportURL=https://github.com/alireza-turk-oglan/soundrecorder
AppUpdatesURL=https://github.com/alireza-turk-oglan/soundrecorder
DefaultDirName={autopf}\Sound Recorder
UninstallDisplayIcon={app}\soundrecorder.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\alireza\Desktop
OutputBaseFilename=soundrecorder
SetupIconFile=D:\Projects\App\installer-soundrecorder\soundrecorder-windows-x64\app_icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Projects\App\installer-soundrecorder\soundrecorder-windows-x64\soundrecorder.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\App\installer-soundrecorder\soundrecorder-windows-x64\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Sound Recorder"; Filename: "{app}\soundrecorder.exe"
Name: "{autodesktop}\Sound Recorder"; Filename: "{app}\soundrecorder.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\soundrecorder.exe"; Description: "{cm:LaunchProgram,Sound Recorder}"; Flags: nowait postinstall skipifsilent

